name: futebol_ml_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy=2.2.5
  - pandas=2.2.3
  - matplotlib=3.10.3
  - seaborn=0.13.2
  - scikit-learn=1.7.0
  - scipy=1.15.3
  - xgboost=3.0.2
  - openpyxl=3.1.5
  - scikit-posthocs
  - tqdm
  - pip
  - pip:
      - joblib==1.5.1
      - pillow==11.2.1

